### ISSUE TITLE
getting error while executing command on remote server

### ISSUE THREAD

**Issue by manoj-compro** [francisminu/IISRESET-npm-package#1]
let data = {
    "username": "username",
    "password": "",
    "serverIpAddress": "192.168.1.92",
    "name": "",
  "directory": "F:\test",
    "command": "mkdir test"
};

serverAdmin.performRemoteCommands(data,(err, stdout, stderr) => {
     console.log('Response: ', err)
    });

Error : Response:  { Error: Command failed: F:\SIMS\Modules\DeploymentScripts\Gulp\Deployment\node_modules\windows-server-admin\PsExec64.exe -s \\192.168.1.92 -u kushagra -p  C: mkdir test
The system cannot find the file specified.
Starting mkdir on 192.168.1.92... 192.168.1.92...
PsExec could not start mkdir on 192.168.1.92:

    at ChildProcess.exithandler (child_process.js:276:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 2,
  signal: null,
  cmd: 'F:\\SIMS\\Modules\\DeploymentScripts\\Gulp\\Deployment\\node_modules\\windows-server-admin\\PsExec64.exe -s \\\\192.168.1.92 -u kushagra -p  C: mkdir test' }

There is no password set on remote server

**Comment by francisminu** [comment]
Did you give any password in there? I see that entry as null. I will take a look to see if there is any issue, even after passing the password
